#!/usr/bin/env bash
# ==============================================================================
#  MyBookShelf — Production Deploy Script
#  Stack  : Django + Gunicorn + Nginx
#  Target : Fresh AWS EC2 Ubuntu 22.04 LTS instance
#  Safe   : Idempotent — can be re-run without breaking anything
# ==============================================================================

set -euo pipefail   # -e exit on error, -u unset vars are errors, -o pipefail

# ------------------------------------------------------------------------------
# ★  CONFIGURATION — edit these before running
# ------------------------------------------------------------------------------
APP_NAME="mybookshelf"
REPO_URL="https://github.com/artikmuratovdev/MyBookShelf.git"
BRANCH="main"

APP_DIR="/var/www/${APP_NAME}"
VENV_DIR="${APP_DIR}/.venv"
SOCK_PATH="/run/${APP_NAME}/${APP_NAME}.sock"   # safe runtime socket location

# Auto-detect public IP if no domain is attached yet.
# Replace with your real domain once DNS is pointed to this server.
# e.g. DOMAIN="mybookshelf.com"
DOMAIN="django-bookshelf.artikmuratov.uz"

DJANGO_SECRET_KEY="${DJANGO_SECRET_KEY:-}"   # REQUIRED — set as env var before running

# Dedicated app user — never run app code as root or $USER
APP_USER="www-data"
APP_GROUP="www-data"

# ------------------------------------------------------------------------------
# ★  PRE-FLIGHT CHECKS
# ------------------------------------------------------------------------------
echo "================================================================"
echo "  MyBookShelf — Production Deploy"
echo "  Target host : ${DOMAIN}"
echo "  App dir     : ${APP_DIR}"
echo "================================================================"

if [[ -z "${DJANGO_SECRET_KEY}" ]]; then
    echo ""
    echo "  ERROR: DJANGO_SECRET_KEY is not set!"
    echo "  Generate one and export before running:"
    echo "    export DJANGO_SECRET_KEY=\$(python3 -c \"import secrets; print(secrets.token_urlsafe(50))\")"
    echo ""
    exit 1
fi

# Must be run as root (or via sudo) so systemd/nginx/apt work correctly
if [[ "${EUID}" -ne 0 ]]; then
    echo "  ERROR: Please run with sudo: sudo -E bash deploy.sh"
    exit 1
fi

# ------------------------------------------------------------------------------
# [1/8] Install system packages
# ------------------------------------------------------------------------------
echo ""
echo "[1/8] Installing system packages..."

apt-get update -q
# DEBIAN_FRONTEND=noninteractive  prevents interactive prompts on upgrade
DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3 python3-pip python3-venv \
    git nginx curl \
    --no-install-recommends

# ------------------------------------------------------------------------------
# [2/8] Clone or update repository
# ------------------------------------------------------------------------------
echo ""
echo "[2/8] Fetching application code..."

if [[ -d "${APP_DIR}/.git" ]]; then
    echo "  Existing repo found — pulling latest ${BRANCH}..."
    git -C "${APP_DIR}" fetch origin
    git -C "${APP_DIR}" reset --hard "origin/${BRANCH}"
else
    echo "  Cloning repository..."
    mkdir -p "${APP_DIR}"
    git clone --branch "${BRANCH}" "${REPO_URL}" "${APP_DIR}"
fi

# Ensure www-data can read all application files
chown -R "${APP_USER}:${APP_GROUP}" "${APP_DIR}"
chmod -R 755 "${APP_DIR}"

# ------------------------------------------------------------------------------
# [3/8] Python virtual environment & dependencies
# ------------------------------------------------------------------------------
echo ""
echo "[3/8] Setting up Python virtual environment..."

python3 -m venv "${VENV_DIR}"
# shellcheck source=/dev/null
source "${VENV_DIR}/bin/activate"

pip install --quiet --upgrade pip

if [[ -f "${APP_DIR}/requirements.txt" ]]; then
    echo "  Installing from requirements.txt..."
    pip install --quiet -r "${APP_DIR}/requirements.txt"
else
    echo "  No requirements.txt found — installing core stack..."
    pip install --quiet django gunicorn pillow
fi

# Always ensure gunicorn and django-environ are present
pip install --quiet "gunicorn>=21.0" "django-environ>=0.11"

deactivate

# ------------------------------------------------------------------------------
# [4/8] Create .env and patch settings.py to read it
# ------------------------------------------------------------------------------
echo ""
echo "[4/8] Writing .env file..."

ENV_FILE="${APP_DIR}/.env"

# Build ALLOWED_HOSTS: always include the IP, plus _ (Nginx health checks)
ALLOWED_HOSTS="${DOMAIN},localhost,127.0.0.1"

cat > "${ENV_FILE}" << EOF
# Auto-generated by deploy.sh — do not commit this file
SECRET_KEY=${DJANGO_SECRET_KEY}
DEBUG=False
ALLOWED_HOSTS=${ALLOWED_HOSTS}
STATIC_ROOT=${APP_DIR}/staticfiles
MEDIA_ROOT=${APP_DIR}/media
EOF

chown "${APP_USER}:${APP_GROUP}" "${ENV_FILE}"
chmod 640 "${ENV_FILE}"   # readable only by owner (www-data) and group

# Patch settings.py to load .env via django-environ (only once, idempotent)
SETTINGS="${APP_DIR}/config/settings.py"
ENVIRON_HEADER="# >>> django-environ block (added by deploy.sh)"

if ! grep -q "${ENVIRON_HEADER}" "${SETTINGS}"; then
    echo "  Patching config/settings.py to read .env..."
    # Prepend the environ block right after the existing imports section
    # We insert at line 1 of the file so it is guaranteed to run first
    python3 - << 'PYEOF'
import re, pathlib

settings_path = pathlib.Path("/var/www/mybookshelf/config/settings.py")
original = settings_path.read_text()

environ_block = '''# >>> django-environ block (added by deploy.sh)
import environ, os
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(os.path.join(os.path.dirname(os.path.dirname(__file__)), ".env"))
# <<< django-environ block

'''

# Replace hard-coded insecure values with env-driven ones
patched = original
patched = re.sub(r"SECRET_KEY\s*=\s*['\"].*?['\"]", "SECRET_KEY = env('SECRET_KEY')", patched)
patched = re.sub(r"DEBUG\s*=\s*(True|False)", "DEBUG = env('DEBUG')", patched)
patched = re.sub(r"ALLOWED_HOSTS\s*=\s*\[.*?\]", "ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost'])", patched)

# Add STATIC_ROOT if missing
if "STATIC_ROOT" not in patched:
    patched += "\nSTATIC_ROOT = env('STATIC_ROOT', default=str(BASE_DIR / 'staticfiles'))\n"

# Add MEDIA_ROOT env override if missing
if "MEDIA_ROOT" not in patched:
    patched += "\nMEDIA_ROOT = env('MEDIA_ROOT', default=str(BASE_DIR / 'media'))\n"

settings_path.write_text(environ_block + patched)
print("  settings.py patched successfully.")
PYEOF
fi

# ------------------------------------------------------------------------------
# [5/8] Django management commands
# ------------------------------------------------------------------------------
echo ""
echo "[5/8] Running Django management commands..."

# Run as www-data so created files are owned correctly
sudo -u "${APP_USER}" "${VENV_DIR}/bin/python" "${APP_DIR}/manage.py" migrate --noinput
sudo -u "${APP_USER}" "${VENV_DIR}/bin/python" "${APP_DIR}/manage.py" collectstatic --noinput --clear

# Ensure media dir exists and has correct ownership
mkdir -p "${APP_DIR}/media" "${APP_DIR}/staticfiles"
chown -R "${APP_USER}:${APP_GROUP}" "${APP_DIR}/media" "${APP_DIR}/staticfiles"

# ------------------------------------------------------------------------------
# [6/8] Gunicorn systemd service
# ------------------------------------------------------------------------------
echo ""
echo "[6/8] Configuring Gunicorn systemd service..."

# Runtime socket directory — lives in /run (tmpfs, wiped on reboot, recreated by systemd)
mkdir -p "/run/${APP_NAME}"
chown "${APP_USER}:${APP_GROUP}" "/run/${APP_NAME}"

# /etc/tmpfiles.d ensures /run/<app>/ is recreated after reboot automatically
cat > "/etc/tmpfiles.d/${APP_NAME}.conf" << EOF
d /run/${APP_NAME} 0755 ${APP_USER} ${APP_GROUP} -
EOF

cat > "/etc/systemd/system/${APP_NAME}.service" << EOF
[Unit]
Description=Gunicorn daemon for ${APP_NAME}
Requires=${APP_NAME}.socket
After=network.target

[Service]
Type=notify

# Dedicated system user — never run as root or the deploy user
User=${APP_USER}
Group=${APP_GROUP}

WorkingDirectory=${APP_DIR}
EnvironmentFile=${ENV_FILE}

# Gunicorn will pick up the socket from the matching .socket unit
ExecStart=${VENV_DIR}/bin/gunicorn \
    --workers 3 \
    --bind unix:${SOCK_PATH} \
    --access-logfile /var/log/${APP_NAME}/access.log \
    --error-logfile  /var/log/${APP_NAME}/error.log \
    --capture-output \
    --log-level info \
    config.wsgi:application

ExecReload=/bin/kill -s HUP \$MAINPID
KillMode=mixed
TimeoutStopSec=5
PrivateTmp=true
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

# Companion .socket unit — lets systemd pass the accepted fd to gunicorn
cat > "/etc/systemd/system/${APP_NAME}.socket" << EOF
[Unit]
Description=Gunicorn socket for ${APP_NAME}

[Socket]
ListenStream=${SOCK_PATH}
SocketUser=${APP_USER}
SocketGroup=${APP_GROUP}
SocketMode=0660

[Install]
WantedBy=sockets.target
EOF

# Log directory
mkdir -p "/var/log/${APP_NAME}"
chown "${APP_USER}:${APP_GROUP}" "/var/log/${APP_NAME}"

systemctl daemon-reload
systemctl enable --now "${APP_NAME}.socket"

# Restart the service if it was already running, otherwise start it
if systemctl is-active --quiet "${APP_NAME}"; then
    systemctl restart "${APP_NAME}"
else
    systemctl start "${APP_NAME}"
fi
systemctl enable "${APP_NAME}"

# ------------------------------------------------------------------------------
# [7/8] Nginx configuration
# ------------------------------------------------------------------------------
echo ""
echo "[7/8] Configuring Nginx..."

NGINX_CONF="/etc/nginx/sites-available/${APP_NAME}"

cat > "${NGINX_CONF}" << EOF
# MyBookShelf — Nginx configuration
# Works with IP address only; add your domain to server_name once DNS is ready.

upstream ${APP_NAME}_gunicorn {
    server unix:${SOCK_PATH};
}

server {
    listen 80;

    # _ matches any Host header — safe for IP-only access.
    # Replace with your real domain when DNS is pointed here.
    server_name ${DOMAIN} _;

    client_max_body_size 20M;

    access_log /var/log/nginx/${APP_NAME}_access.log;
    error_log  /var/log/nginx/${APP_NAME}_error.log;

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    # Static files — alias is correct here; do NOT mix with root
    location /static/ {
        alias ${APP_DIR}/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    # Media files — same pattern as static
    location /media/ {
        alias ${APP_DIR}/media/;
        expires 7d;
    }

    # Everything else → Gunicorn
    location / {
        proxy_pass         http://${APP_NAME}_gunicorn;
        proxy_http_version 1.1;

        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        proxy_connect_timeout 60s;
        proxy_read_timeout    60s;
    }
}
EOF

# Enable site, disable default placeholder
ln -sf "${NGINX_CONF}" "/etc/nginx/sites-enabled/${APP_NAME}"
rm -f /etc/nginx/sites-enabled/default

# Test config before applying
nginx -t
systemctl restart nginx
systemctl enable nginx

# ------------------------------------------------------------------------------
# [8/8] AWS note — skip UFW (Security Groups handle the firewall)
# ------------------------------------------------------------------------------
echo ""
echo "[8/8] Firewall note:"
echo "  ✔  UFW is intentionally NOT enabled on AWS EC2."
echo "  ✔  Use your EC2 Security Group to allow port 80 (HTTP) and 22 (SSH)."
echo "  ✔  Add port 443 (HTTPS) when you attach a domain and install Certbot."

# ------------------------------------------------------------------------------
# ★  FINAL STATUS CHECK
# ------------------------------------------------------------------------------
echo ""
echo "================================================================"

GUNICORN_STATUS=$(systemctl is-active "${APP_NAME}" 2>/dev/null || echo "inactive")
NGINX_STATUS=$(systemctl is-active nginx 2>/dev/null || echo "inactive")

if [[ "${GUNICORN_STATUS}" == "active" && "${NGINX_STATUS}" == "active" ]]; then
    echo "  ✅  Deploy successful!"
else
    echo "  ⚠️  Deploy finished but some services may need attention:"
    echo "      Gunicorn : ${GUNICORN_STATUS}"
    echo "      Nginx    : ${NGINX_STATUS}"
fi

echo ""
echo "  🌐 URL         : http://${DOMAIN}"
echo "  📁 App dir     : ${APP_DIR}"
echo "  📋 Logs        : journalctl -u ${APP_NAME} -f"
echo "                   tail -f /var/log/${APP_NAME}/error.log"
echo ""
echo "  ── Next steps ──────────────────────────────────────────────"
echo "  1. Open port 80 in your EC2 Security Group (if not already done)."
echo "  2. Assign an Elastic IP so your server IP stays fixed."
echo "  3. Point your domain's A record to the Elastic IP."
echo "  4. Install HTTPS (free, automatic):"
echo "       sudo apt install certbot python3-certbot-nginx -y"
echo "       sudo certbot --nginx -d ${DOMAIN}"
echo "  5. Re-deploy after code changes:"
echo "       sudo -E bash ${APP_DIR}/deploy.sh"
echo "================================================================"
