# Generated by Django 6.0.2 on 2026-02-28 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Kitob muqovasi (ixtiyoriy)', null=True, upload_to='books/covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(default='', help_text='Faqat PDF formatdagi fayllar ruxsat etiladi.', upload_to='books/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
            preserve_default=False,
        ),
    ]
